"""empty message

Revision ID: 54b578be3c27
Revises: 
Create Date: 2024-02-25 21:35:19.345987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54b578be3c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('commentaire_blog', schema=None) as batch_op:
        batch_op.alter_column('contenu',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=2500000),
               existing_nullable=True)
        batch_op.alter_column('auteur',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('commentaire_formation', schema=None) as batch_op:
        batch_op.alter_column('contenu',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('auteur',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('conferencier',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('lien',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('lieu',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('content_formation', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('offre', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('fonc',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('postul', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=100000),
               existing_nullable=True)
        batch_op.alter_column('cv',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255000),
               existing_nullable=True)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('func',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('souscripconf', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('souscription_formation', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    with op.batch_alter_table('theme_formation', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.String(length=250000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_formation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('souscription_formation', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('souscripconf', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('func',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('imagePath',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('postul', schema=None) as batch_op:
        batch_op.alter_column('cv',
               existing_type=sa.String(length=255000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('offre', schema=None) as batch_op:
        batch_op.alter_column('fonc',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('content_formation', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.alter_column('lieu',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('lien',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('conferencier',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('imagePath',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('commentaire_formation', schema=None) as batch_op:
        batch_op.alter_column('auteur',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('contenu',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('commentaire_blog', schema=None) as batch_op:
        batch_op.alter_column('auteur',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('contenu',
               existing_type=sa.String(length=2500000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('imagePath',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=250000),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=True)

    # ### end Alembic commands ###
